# Generated by Django 3.2.25 on 2024-08-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
